import { BrandedService } from '@/types';

export const BRANDED_SERVICES: Record<string, BrandedService> = {
  Netflix: {
    name: 'Netflix',
    color: '#E50914',
    bgColor: '#1a0000',
    icon: '🎬',
    category: 'entertainment',
    defaultAmount: 15.49,
    billing_cycle: 'monthly',
    website: 'https://netflix.com',
  },
  Spotify: {
    name: 'Spotify',
    color: '#1DB954',
    bgColor: '#001a08',
    icon: '🎵',
    category: 'music',
    defaultAmount: 9.99,
    billing_cycle: 'monthly',
    website: 'https://spotify.com',
  },
  'Apple Music': {
    name: 'Apple Music',
    color: '#fc3c44',
    bgColor: '#1a0004',
    icon: '🎧',
    category: 'music',
    defaultAmount: 10.99,
    billing_cycle: 'monthly',
    website: 'https://music.apple.com',
  },
  'YouTube Premium': {
    name: 'YouTube Premium',
    color: '#FF0000',
    bgColor: '#1a0000',
    icon: '▶️',
    category: 'entertainment',
    defaultAmount: 13.99,
    billing_cycle: 'monthly',
    website: 'https://youtube.com',
  },
  'Disney+': {
    name: 'Disney+',
    color: '#0063e5',
    bgColor: '#000d1a',
    icon: '✨',
    category: 'entertainment',
    defaultAmount: 7.99,
    billing_cycle: 'monthly',
    website: 'https://disneyplus.com',
  },
  'Amazon Prime': {
    name: 'Amazon Prime',
    color: '#00A8E1',
    bgColor: '#00111a',
    icon: '📦',
    category: 'shopping',
    defaultAmount: 14.99,
    billing_cycle: 'monthly',
    website: 'https://amazon.com',
  },
  'Apple iCloud': {
    name: 'Apple iCloud',
    color: '#3692f5',
    bgColor: '#00091a',
    icon: '☁️',
    category: 'cloud',
    defaultAmount: 2.99,
    billing_cycle: 'monthly',
    website: 'https://icloud.com',
  },
  'Google One': {
    name: 'Google One',
    color: '#4285F4',
    bgColor: '#00081a',
    icon: '💾',
    category: 'cloud',
    defaultAmount: 2.99,
    billing_cycle: 'monthly',
    website: 'https://one.google.com',
  },
  'Microsoft 365': {
    name: 'Microsoft 365',
    color: '#0078d4',
    bgColor: '#00091a',
    icon: '💼',
    category: 'productivity',
    defaultAmount: 9.99,
    billing_cycle: 'monthly',
    website: 'https://microsoft.com',
  },
  Notion: {
    name: 'Notion',
    color: '#ffffff',
    bgColor: '#111111',
    icon: '📝',
    category: 'productivity',
    defaultAmount: 8.0,
    billing_cycle: 'monthly',
    website: 'https://notion.so',
  },
  'GitHub Pro': {
    name: 'GitHub Pro',
    color: '#6e40c9',
    bgColor: '#0d0016',
    icon: '🐙',
    category: 'productivity',
    defaultAmount: 4.0,
    billing_cycle: 'monthly',
    website: 'https://github.com',
  },
  'Xbox Game Pass': {
    name: 'Xbox Game Pass',
    color: '#107C10',
    bgColor: '#001a00',
    icon: '🎮',
    category: 'gaming',
    defaultAmount: 14.99,
    billing_cycle: 'monthly',
    website: 'https://xbox.com',
  },
  'PlayStation Plus': {
    name: 'PlayStation Plus',
    color: '#006FCD',
    bgColor: '#00081a',
    icon: '🕹️',
    category: 'gaming',
    defaultAmount: 59.99,
    billing_cycle: 'yearly',
    website: 'https://playstation.com',
  },
  Duolingo: {
    name: 'Duolingo',
    color: '#58CC02',
    bgColor: '#051a00',
    icon: '🦉',
    category: 'education',
    defaultAmount: 6.99,
    billing_cycle: 'monthly',
    website: 'https://duolingo.com',
  },
  Headspace: {
    name: 'Headspace',
    color: '#F47D31',
    bgColor: '#1a0a00',
    icon: '🧘',
    category: 'fitness',
    defaultAmount: 12.99,
    billing_cycle: 'monthly',
    website: 'https://headspace.com',
  },
  Calm: {
    name: 'Calm',
    color: '#4A90A4',
    bgColor: '#001015',
    icon: '🌊',
    category: 'fitness',
    defaultAmount: 14.99,
    billing_cycle: 'monthly',
    website: 'https://calm.com',
  },
  Dropbox: {
    name: 'Dropbox',
    color: '#0061FF',
    bgColor: '#00091a',
    icon: '📂',
    category: 'cloud',
    defaultAmount: 11.99,
    billing_cycle: 'monthly',
    website: 'https://dropbox.com',
  },
  'New York Times': {
    name: 'New York Times',
    color: '#ffffff',
    bgColor: '#111111',
    icon: '📰',
    category: 'news',
    defaultAmount: 17.0,
    billing_cycle: 'monthly',
    website: 'https://nytimes.com',
  },
  HBO: {
    name: 'HBO Max',
    color: '#B535F6',
    bgColor: '#120019',
    icon: '📺',
    category: 'entertainment',
    defaultAmount: 15.99,
    billing_cycle: 'monthly',
    website: 'https://max.com',
  },
  Hulu: {
    name: 'Hulu',
    color: '#1ce783',
    bgColor: '#001a0d',
    icon: '🟢',
    category: 'entertainment',
    defaultAmount: 7.99,
    billing_cycle: 'monthly',
    website: 'https://hulu.com',
  },
};

export const CATEGORY_COLORS: Record<string, string> = {
  entertainment: '#E50914',
  music: '#1DB954',
  productivity: '#0078d4',
  gaming: '#107C10',
  fitness: '#FF6B35',
  news: '#8b8b8b',
  shopping: '#FF9900',
  cloud: '#4285F4',
  education: '#58CC02',
  other: '#8b5cf6',
};

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'AU$', name: 'Australian Dollar' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso' },
];

export const CURRENCY_SYMBOLS: Record<string, string> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c.symbol])
);

export const ACCENT_COLORS = [
  { name: 'Emerald', value: '#10b981' },
  { name: 'Teal', value: '#14b8a6' },
  { name: 'Slate Blue', value: '#6366f1' },
  { name: 'Sky', value: '#0ea5e9' },
  { name: 'Rose', value: '#f43f5e' },
  { name: 'Amber', value: '#f59e0b' },
  { name: 'Orange', value: '#f97316' },
  { name: 'Pink', value: '#ec4899' },
];

export const TIMEZONES = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Asia/Kolkata',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Australia/Sydney',
];
